#default port where the service will be started
server:
  port: 8083 

#tells about the Eureka server details and its refresh time 
eureka:     
  instance:
#    leaseRenewalIntervalInSeconds: 1
 #   leaseExpirationDurationInSeconds: 2
    preferIpAddress: true 
  client:
    serviceUrl:
      # localhost
       defaultZone: http://localhost:8761/eureka/
      # docker
      # defaultZone: http://sa-discovery:8761/eureka/
 #   healthcheck:
 #     enabled: true
 #   lease:
 #     duration: 5
 
spring:   
  application:
    name: sa-mysql   #current service name to be used by the eureka server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #1. localhost in devlopment machine - working
    jdbc-url: jdbc:mysql://localhost:3306/studyaid
    username: root
    password: root
    
    #2. Docker desktop at windows -working
    #jdbcUrl: jdbc:mysql://172.17.0.1:3306/studyaid
    #username: root
    #password: root
    
    #3. Docker desktop AWS
    #jdbc-url: jdbc:mysql://host.docker.internal:3306/studyaid
    #username: admin
    #password: studyaid     
   
    
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc. 
    

#logging:
#  level:
#    com.sa.display: DEBUG
