#default port where the service will be started
server:
  port: 8082  

#tells about the Eureka server details and its refresh time 
eureka:     
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:   
  application:
    name: display-ui   #current service name to be used by the eureka server
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/studyaid
    username: root
    password: root    
   
    
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc. 
    

#logging:
#  level:
#    com.sa.display: DEBUG
